A Bash script has been created for task 8
arturhostiuk99/DevOps-Cisco-TeamA pull request #12
Opened 2023-10-03 10:03 UTC by yuriikovtsun1

![Знімок екрана 2023-10-03 о 12 59 15](https://github.com/arturhostiuk99/DevOps-Cisco-TeamA/assets/146677069/78fcea83-76ea-4292-80fb-2d4814436bad)

2023-10-03 16:51 UTC, arturhostiuk99 approved these changes

2023-10-04 13:37 UTC, MaksymukNatalia approved these changes

2023-10-04 13:41 UTC, arturhostiuk99 requested changes

2023-10-04 13:41 UTC, arturhostiuk99 commented on README.md
> -# DevOps-Cisco-TeamA
No need to add instruction to main README.md

2023-10-04 13:41 UTC, arturhostiuk99 commented on 1-python-bash/7-task/file-counter-task7.sh
> +#!/bin/bash
This script is related to other task (task 7)

2023-10-04 14:36 UTC, Kova1DM approved these changes

2023-10-04 18:10 UTC, arturhostiuk99 approved these changes

2023-10-04 18:13 UTC, merged