Complete task 6 - Bash - Koval Iaroslav
arturhostiuk99/DevOps-Cisco-TeamA pull request #16
Opened 2023-10-03 12:10 UTC by IaKoval

Bash script for task 2

2023-10-03 12:50 UTC, Kova1DM approved these changes

2023-10-03 16:26 UTC, yuriikovtsun1 approved these changes

2023-10-04 12:24 UTC, MaksymukNatalia commented
It is a good practice to use only English in scripts. It is also very cool that it searches for text in nested directories, but does not display the path to the files.Also, fill out the pr (use a template, for example)

2023-10-04 14:23 UTC, arturhostiuk99 requested changes

2023-10-04 18:02 UTC, arturhostiuk99 approved these changes

2023-10-04 19:29 UTC, merged